[package]
name = "lateen"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
chrono = { version = "0.4.45", features = ["serde"] }
chrono-tz = "0.10.4"
futures-lite = { version = "2.6.1", default-features = false }
gpui = { package = "gpui", git = "https://github.com/someone13574/gpui-ce", branch = "swash-hinting-bug", version = "0.2.2" }
gpui_platform = { git = "https://github.com/someone13574/gpui-ce", features = ["font-kit", "wayland", "x11"], branch = "swash-hinting-bug", version = "0.1.0" }
gpui_tokio = { git = "https://github.com/someone13574/gpui-ce", branch = "swash-hinting-bug", version = "0.1.0" }
reqwest = { version = "0.13", default-features = false, features = ["http2", "rustls"] }
rust-embed = { version = "8.12.0", features = ["debug-embed", "include-exclude"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
unicode-segmentation = "1.13.3"
zbus = "5.19.0"
